name: Publish

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      tag_name:
        description: |
            Tag name that the major tag will point to
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/publish-action@23f4c6f12633a2da8f44938b71fde9afec138fb4 # v0.4.0
        with:
          source-tag: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}
